name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Zip the extension
      run: 
        zip -r chrome-extension-${GITHUB_REF##*/}.zip . -x ".github/*" ".git/*"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-${GITHUB_REF##*/}.zip
        path: chrome-extension-${GITHUB_REF##*/}.zip
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: dist/file.zip
        extension-id: tabstar
        client-id: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
        client-secret: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}